ALTER TABLE ports
    ADD COLUMN IF NOT EXISTS port_type_name VARCHAR(80),
    ADD COLUMN IF NOT EXISTS country_name VARCHAR(120),
    ADD COLUMN IF NOT EXISTS state_code VARCHAR(30),
    ADD COLUMN IF NOT EXISTS port_operator VARCHAR(120),
    ADD COLUMN IF NOT EXISTS port_no INTEGER,
    ADD COLUMN IF NOT EXISTS time_zone_code VARCHAR(50),
    ADD COLUMN IF NOT EXISTS latitude_text VARCHAR(30),
    ADD COLUMN IF NOT EXISTS longitude_text VARCHAR(30),
    ADD COLUMN IF NOT EXISTS region_code VARCHAR(50),
    ADD COLUMN IF NOT EXISTS loadline_zone VARCHAR(50),
    ADD COLUMN IF NOT EXISTS std_gmt_offset NUMERIC(5,2),
    ADD COLUMN IF NOT EXISTS dst_gmt_offset NUMERIC(5,2);
