/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AddressBookRouteImport } from './routes/address-book'
import { Route as AnalyzerRouteImport } from './routes/analyzer'
import { Route as BunkerSimulatorRouteImport } from './routes/bunker-simulator'
import { Route as CargoReletRouteImport } from './routes/cargo-relet'
import { Route as Co2EmissionRouteImport } from './routes/co2-emission'
import { Route as EstimateListRouteImport } from './routes/estimate-list'
import { Route as FreightSimulatorRouteImport } from './routes/freight-simulator'
import { Route as LaytimeRouteImport } from './routes/laytime'
import { Route as LinerTermsRouteImport } from './routes/liner-terms'
import { Route as LoadableQuantityCalcRouteImport } from './routes/loadable-quantity-calc'
import { Route as NewCargoRouteImport } from './routes/new-cargo'
import { Route as NewPortRouteImport } from './routes/new-port'
import { Route as NewVesselRouteImport } from './routes/new-vessel'
import { Route as OperationRouteImport } from './routes/operation'
import { Route as TimeCharterRouteImport } from './routes/time-charter'
import { Route as TimeCharterPartyRouteImport } from './routes/time-charter-party'
import { Route as VoyageCharterPartyRouteImport } from './routes/voyage-charter-party'
import { Route as VoyageEstimatorRouteImport } from './routes/voyage-estimator'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AddressBookRoute = AddressBookRouteImport.update({
  id: '/address-book',
  path: '/address-book',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyzerRoute = AnalyzerRouteImport.update({
  id: '/analyzer',
  path: '/analyzer',
  getParentRoute: () => rootRouteImport,
} as any)
const BunkerSimulatorRoute = BunkerSimulatorRouteImport.update({
  id: '/bunker-simulator',
  path: '/bunker-simulator',
  getParentRoute: () => rootRouteImport,
} as any)
const CargoReletRoute = CargoReletRouteImport.update({
  id: '/cargo-relet',
  path: '/cargo-relet',
  getParentRoute: () => rootRouteImport,
} as any)
const Co2EmissionRoute = Co2EmissionRouteImport.update({
  id: '/co2-emission',
  path: '/co2-emission',
  getParentRoute: () => rootRouteImport,
} as any)
const EstimateListRoute = EstimateListRouteImport.update({
  id: '/estimate-list',
  path: '/estimate-list',
  getParentRoute: () => rootRouteImport,
} as any)
const FreightSimulatorRoute = FreightSimulatorRouteImport.update({
  id: '/freight-simulator',
  path: '/freight-simulator',
  getParentRoute: () => rootRouteImport,
} as any)
const LaytimeRoute = LaytimeRouteImport.update({
  id: '/laytime',
  path: '/laytime',
  getParentRoute: () => rootRouteImport,
} as any)
const LinerTermsRoute = LinerTermsRouteImport.update({
  id: '/liner-terms',
  path: '/liner-terms',
  getParentRoute: () => rootRouteImport,
} as any)
const LoadableQuantityCalcRoute = LoadableQuantityCalcRouteImport.update({
  id: '/loadable-quantity-calc',
  path: '/loadable-quantity-calc',
  getParentRoute: () => rootRouteImport,
} as any)
const NewCargoRoute = NewCargoRouteImport.update({
  id: '/new-cargo',
  path: '/new-cargo',
  getParentRoute: () => rootRouteImport,
} as any)
const NewPortRoute = NewPortRouteImport.update({
  id: '/new-port',
  path: '/new-port',
  getParentRoute: () => rootRouteImport,
} as any)
const NewVesselRoute = NewVesselRouteImport.update({
  id: '/new-vessel',
  path: '/new-vessel',
  getParentRoute: () => rootRouteImport,
} as any)
const OperationRoute = OperationRouteImport.update({
  id: '/operation',
  path: '/operation',
  getParentRoute: () => rootRouteImport,
} as any)
const TimeCharterRoute = TimeCharterRouteImport.update({
  id: '/time-charter',
  path: '/time-charter',
  getParentRoute: () => rootRouteImport,
} as any)
const TimeCharterPartyRoute = TimeCharterPartyRouteImport.update({
  id: '/time-charter-party',
  path: '/time-charter-party',
  getParentRoute: () => rootRouteImport,
} as any)
const VoyageCharterPartyRoute = VoyageCharterPartyRouteImport.update({
  id: '/voyage-charter-party',
  path: '/voyage-charter-party',
  getParentRoute: () => rootRouteImport,
} as any)
const VoyageEstimatorRoute = VoyageEstimatorRouteImport.update({
  id: '/voyage-estimator',
  path: '/voyage-estimator',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/address-book': typeof AddressBookRoute
  '/analyzer': typeof AnalyzerRoute
  '/bunker-simulator': typeof BunkerSimulatorRoute
  '/cargo-relet': typeof CargoReletRoute
  '/co2-emission': typeof Co2EmissionRoute
  '/estimate-list': typeof EstimateListRoute
  '/freight-simulator': typeof FreightSimulatorRoute
  '/laytime': typeof LaytimeRoute
  '/liner-terms': typeof LinerTermsRoute
  '/loadable-quantity-calc': typeof LoadableQuantityCalcRoute
  '/new-cargo': typeof NewCargoRoute
  '/new-port': typeof NewPortRoute
  '/new-vessel': typeof NewVesselRoute
  '/operation': typeof OperationRoute
  '/time-charter': typeof TimeCharterRoute
  '/time-charter-party': typeof TimeCharterPartyRoute
  '/voyage-charter-party': typeof VoyageCharterPartyRoute
  '/voyage-estimator': typeof VoyageEstimatorRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/address-book': typeof AddressBookRoute
  '/analyzer': typeof AnalyzerRoute
  '/bunker-simulator': typeof BunkerSimulatorRoute
  '/cargo-relet': typeof CargoReletRoute
  '/co2-emission': typeof Co2EmissionRoute
  '/estimate-list': typeof EstimateListRoute
  '/freight-simulator': typeof FreightSimulatorRoute
  '/laytime': typeof LaytimeRoute
  '/liner-terms': typeof LinerTermsRoute
  '/loadable-quantity-calc': typeof LoadableQuantityCalcRoute
  '/new-cargo': typeof NewCargoRoute
  '/new-port': typeof NewPortRoute
  '/new-vessel': typeof NewVesselRoute
  '/operation': typeof OperationRoute
  '/time-charter': typeof TimeCharterRoute
  '/time-charter-party': typeof TimeCharterPartyRoute
  '/voyage-charter-party': typeof VoyageCharterPartyRoute
  '/voyage-estimator': typeof VoyageEstimatorRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/address-book': typeof AddressBookRoute
  '/analyzer': typeof AnalyzerRoute
  '/bunker-simulator': typeof BunkerSimulatorRoute
  '/cargo-relet': typeof CargoReletRoute
  '/co2-emission': typeof Co2EmissionRoute
  '/estimate-list': typeof EstimateListRoute
  '/freight-simulator': typeof FreightSimulatorRoute
  '/laytime': typeof LaytimeRoute
  '/liner-terms': typeof LinerTermsRoute
  '/loadable-quantity-calc': typeof LoadableQuantityCalcRoute
  '/new-cargo': typeof NewCargoRoute
  '/new-port': typeof NewPortRoute
  '/new-vessel': typeof NewVesselRoute
  '/operation': typeof OperationRoute
  '/time-charter': typeof TimeCharterRoute
  '/time-charter-party': typeof TimeCharterPartyRoute
  '/voyage-charter-party': typeof VoyageCharterPartyRoute
  '/voyage-estimator': typeof VoyageEstimatorRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/address-book'
    | '/analyzer'
    | '/bunker-simulator'
    | '/cargo-relet'
    | '/co2-emission'
    | '/estimate-list'
    | '/freight-simulator'
    | '/laytime'
    | '/liner-terms'
    | '/loadable-quantity-calc'
    | '/new-cargo'
    | '/new-port'
    | '/new-vessel'
    | '/operation'
    | '/time-charter'
    | '/time-charter-party'
    | '/voyage-charter-party'
    | '/voyage-estimator'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/address-book'
    | '/analyzer'
    | '/bunker-simulator'
    | '/cargo-relet'
    | '/co2-emission'
    | '/estimate-list'
    | '/freight-simulator'
    | '/laytime'
    | '/liner-terms'
    | '/loadable-quantity-calc'
    | '/new-cargo'
    | '/new-port'
    | '/new-vessel'
    | '/operation'
    | '/time-charter'
    | '/time-charter-party'
    | '/voyage-charter-party'
    | '/voyage-estimator'
  id:
    | '__root__'
    | '/'
    | '/address-book'
    | '/analyzer'
    | '/bunker-simulator'
    | '/cargo-relet'
    | '/co2-emission'
    | '/estimate-list'
    | '/freight-simulator'
    | '/laytime'
    | '/liner-terms'
    | '/loadable-quantity-calc'
    | '/new-cargo'
    | '/new-port'
    | '/new-vessel'
    | '/operation'
    | '/time-charter'
    | '/time-charter-party'
    | '/voyage-charter-party'
    | '/voyage-estimator'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AddressBookRoute: typeof AddressBookRoute
  AnalyzerRoute: typeof AnalyzerRoute
  BunkerSimulatorRoute: typeof BunkerSimulatorRoute
  CargoReletRoute: typeof CargoReletRoute
  Co2EmissionRoute: typeof Co2EmissionRoute
  EstimateListRoute: typeof EstimateListRoute
  FreightSimulatorRoute: typeof FreightSimulatorRoute
  LaytimeRoute: typeof LaytimeRoute
  LinerTermsRoute: typeof LinerTermsRoute
  LoadableQuantityCalcRoute: typeof LoadableQuantityCalcRoute
  NewCargoRoute: typeof NewCargoRoute
  NewPortRoute: typeof NewPortRoute
  NewVesselRoute: typeof NewVesselRoute
  OperationRoute: typeof OperationRoute
  TimeCharterRoute: typeof TimeCharterRoute
  TimeCharterPartyRoute: typeof TimeCharterPartyRoute
  VoyageCharterPartyRoute: typeof VoyageCharterPartyRoute
  VoyageEstimatorRoute: typeof VoyageEstimatorRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/address-book': {
      id: '/address-book'
      path: '/address-book'
      fullPath: '/address-book'
      preLoaderRoute: typeof AddressBookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analyzer': {
      id: '/analyzer'
      path: '/analyzer'
      fullPath: '/analyzer'
      preLoaderRoute: typeof AnalyzerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bunker-simulator': {
      id: '/bunker-simulator'
      path: '/bunker-simulator'
      fullPath: '/bunker-simulator'
      preLoaderRoute: typeof BunkerSimulatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cargo-relet': {
      id: '/cargo-relet'
      path: '/cargo-relet'
      fullPath: '/cargo-relet'
      preLoaderRoute: typeof CargoReletRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/co2-emission': {
      id: '/co2-emission'
      path: '/co2-emission'
      fullPath: '/co2-emission'
      preLoaderRoute: typeof Co2EmissionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/estimate-list': {
      id: '/estimate-list'
      path: '/estimate-list'
      fullPath: '/estimate-list'
      preLoaderRoute: typeof EstimateListRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/freight-simulator': {
      id: '/freight-simulator'
      path: '/freight-simulator'
      fullPath: '/freight-simulator'
      preLoaderRoute: typeof FreightSimulatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/laytime': {
      id: '/laytime'
      path: '/laytime'
      fullPath: '/laytime'
      preLoaderRoute: typeof LaytimeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/liner-terms': {
      id: '/liner-terms'
      path: '/liner-terms'
      fullPath: '/liner-terms'
      preLoaderRoute: typeof LinerTermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/loadable-quantity-calc': {
      id: '/loadable-quantity-calc'
      path: '/loadable-quantity-calc'
      fullPath: '/loadable-quantity-calc'
      preLoaderRoute: typeof LoadableQuantityCalcRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/new-cargo': {
      id: '/new-cargo'
      path: '/new-cargo'
      fullPath: '/new-cargo'
      preLoaderRoute: typeof NewCargoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/new-port': {
      id: '/new-port'
      path: '/new-port'
      fullPath: '/new-port'
      preLoaderRoute: typeof NewPortRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/new-vessel': {
      id: '/new-vessel'
      path: '/new-vessel'
      fullPath: '/new-vessel'
      preLoaderRoute: typeof NewVesselRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/operation': {
      id: '/operation'
      path: '/operation'
      fullPath: '/operation'
      preLoaderRoute: typeof OperationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/time-charter': {
      id: '/time-charter'
      path: '/time-charter'
      fullPath: '/time-charter'
      preLoaderRoute: typeof TimeCharterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/time-charter-party': {
      id: '/time-charter-party'
      path: '/time-charter-party'
      fullPath: '/time-charter-party'
      preLoaderRoute: typeof TimeCharterPartyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/voyage-charter-party': {
      id: '/voyage-charter-party'
      path: '/voyage-charter-party'
      fullPath: '/voyage-charter-party'
      preLoaderRoute: typeof VoyageCharterPartyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/voyage-estimator': {
      id: '/voyage-estimator'
      path: '/voyage-estimator'
      fullPath: '/voyage-estimator'
      preLoaderRoute: typeof VoyageEstimatorRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AddressBookRoute: AddressBookRoute,
  AnalyzerRoute: AnalyzerRoute,
  BunkerSimulatorRoute: BunkerSimulatorRoute,
  CargoReletRoute: CargoReletRoute,
  Co2EmissionRoute: Co2EmissionRoute,
  EstimateListRoute: EstimateListRoute,
  FreightSimulatorRoute: FreightSimulatorRoute,
  LaytimeRoute: LaytimeRoute,
  LinerTermsRoute: LinerTermsRoute,
  LoadableQuantityCalcRoute: LoadableQuantityCalcRoute,
  NewCargoRoute: NewCargoRoute,
  NewPortRoute: NewPortRoute,
  NewVesselRoute: NewVesselRoute,
  OperationRoute: OperationRoute,
  TimeCharterRoute: TimeCharterRoute,
  TimeCharterPartyRoute: TimeCharterPartyRoute,
  VoyageCharterPartyRoute: VoyageCharterPartyRoute,
  VoyageEstimatorRoute: VoyageEstimatorRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
