import type { ThemeConfig } from "antd";

export const VE_COLORS = {
  titleBar: "#155B78",
  statusBar: "#0E4F68",
  sectionTitle: "#0E5D80",
  secondary: "#1C78A0",
  editable: "#FFFFFF",
  focus: "#1C78A0",
  alert: "#D32F2F",
  border: "#D8E2EA",
  headerBg: "#E9F1F6",
  headerText: "#334E63",
  subHeaderBg: "#DCEAF1",
  rowAlt: "#F8FBFD",
  summary: "#E6F0F5",
  hover: "#EAF6FB",
  selected: "#D4E8F1",
} as const;

export const VE_FONT_FAMILY = "'Segoe UI', -apple-system, BlinkMacSystemFont, sans-serif";

export const veTheme: ThemeConfig = {
  token: {
    fontFamily: VE_FONT_FAMILY,
    fontSize: 11,
    fontSizeSM: 11,
    fontSizeLG: 12,
    fontSizeHeading5: 12,
    controlHeight: 24,
    controlHeightSM: 22,
    borderRadius: 2,
    borderRadiusSM: 2,
    borderRadiusLG: 2,
    colorPrimary: VE_COLORS.headerBg,
    colorInfo: VE_COLORS.secondary,
    colorBorder: VE_COLORS.border,
    colorBorderSecondary: VE_COLORS.border,
    lineHeight: 1.25,
    paddingXS: 4,
    marginXS: 4,
  },
  components: {
    Table: {
      cellPaddingBlock: 2,
      cellPaddingInline: 4,
      cellPaddingBlockSM: 2,
      cellPaddingInlineSM: 4,
      headerBg: VE_COLORS.headerBg,
      headerColor: VE_COLORS.headerText,
      headerSplitColor: VE_COLORS.border,
      borderColor: VE_COLORS.border,
      rowHoverBg: VE_COLORS.hover,
      fontSize: 11,
      headerBorderRadius: 0,
    },
    Button: {
      fontSize: 12,
      paddingInline: 6,
      defaultBg: "#FFFFFF",
      defaultBorderColor: "#B8CBD8",
      defaultColor: VE_COLORS.sectionTitle,
      defaultHoverBg: "#EAF6FB",
      defaultHoverBorderColor: VE_COLORS.secondary,
      defaultHoverColor: "#FFFFFF",
      colorPrimary: VE_COLORS.secondary,
      colorPrimaryHover: VE_COLORS.secondary,
      primaryColor: "#FFFFFF",
    },
    Input: {
      paddingInline: 4,
      paddingBlock: 0,
      fontSize: 11,
      activeBorderColor: VE_COLORS.focus,
      hoverBorderColor: VE_COLORS.focus,
    },
    InputNumber: { paddingInline: 4, fontSize: 11 },
    Select: {
      fontSize: 11,
      optionFontSize: 11,
      optionPadding: "1px 6px",
      activeBorderColor: VE_COLORS.focus,
      hoverBorderColor: VE_COLORS.focus,
    },
    DatePicker: { fontSize: 11, paddingInline: 4 },
    Tabs: { fontSize: 12, horizontalItemPadding: "3px 8px", horizontalMargin: "0 0 4px 0" },
    Checkbox: { fontSize: 11 },
    Card: { paddingLG: 6, fontSize: 11 },
    Slider: { railSize: 3, handleSize: 8, handleSizeHover: 10 },
  },
};
