// ============================================================
//  TIÊU ĐỀ / NHÃN TIẾNG VIỆT — Sửa toàn bộ form tại đây
//  (Áp dụng cho: Estimation, Operation, TimeCharter,
//                LoadableQuantity, CargoRelet, NewVesselDialog)
//  Quy ước: Giữ nguyên các thuật ngữ chuyên ngành viết tắt
//  (MV, DWT, TPC, MT, ECA, VLSFO, MGO, ULSFO, FIO, IMO, GRT,
//   NRT, LOA, CBM, CBF, TPI, SCNT, PNI, CP, A.Comm, Brkg, Frt,
//   ILOHC, C.E.V., W.F, Spd, Sea, Dem, Des, SUEZ, PANAMA, KIEL,
//   SAG/HOG, HA/HO, USD…)
// ============================================================

export const L = {
  // ---------- Ribbon chung ----------
  new: "Mới",
  delete: "Xóa",
  save: "Lưu",
  saveAs: "Lưu thành",
  open: "Mở",
  reload: "Tải lại",
  undo: "Hoàn tác",
  redo: "Làm lại",
  increase: "Phóng to",
  decrease: "Thu nhỏ",
  options: "Tùy chọn",
  loadContract: "Tải hợp đồng",
  relatedContract: "HĐ\nliên quan",
  attachment: "Đính kèm",
  balancing: "Cân đối",
  vesselMonitor: "Theo dõi\ntàu",
  toBeUpdated: "Chờ\ncập nhật",
  reportNotice: "Báo cáo &\nThông báo",
  createMilestone: "Tạo\ncột mốc",

  // ---------- Tabs / Trạng thái ----------
  voyage1: "hành trình 1",
  voyage2: "hành trình 2",
  cargoRelet1: "cargo relet 1",
  timeCharter1: "time charter 1",
  initial: "Khởi tạo",
  active: "Đang hoạt động",
  status: "Trạng thái",
  ongoing: "Đang thực hiện",
  lastUpdate: "Cập nhật lần cuối",

  // ---------- Vessel Particular ----------
  vesselParticular: "Thông số tàu",
  mv: "MV",
  dwt: "DWT",
  draftM: "Mớn nước (M)",
  tpc: "TPC",
  built: "Năm đóng",
  kind: "Loại",
  type: "Kiểu",

  // ---------- Bunker / Speed table ----------
  fixPortConsumption: "Cố định tiêu hao tại cảng",
  ballast: "Ballast",
  laden: "Có hàng",
  main: "Máy chính",
  sub: "Máy phụ",
  channel: "Luồng",
  idle: "Nghỉ",
  work: "Làm hàng",
  sea: "Biển",

  // ---------- Cargo ----------
  cargo: "Hàng hóa",
  account: "Khách hàng",
  cargoName: "Tên hàng",
  loadingPort: "Cảng xếp",
  dischargingPort: "Cảng dỡ",
  quantity: "Khối lượng",
  term: "Điều kiện",
  totalFreight: "Tổng cước",
  aComm: "A. Comm",
  brkg: "Brkg",
  frt: "Frt",
  netFrt: "Cước thực",
  frtTax: "Thuế cước",
  linerTerm: "ĐK Liner",
  linerTerms: "ĐK Liner",
  loadableQtyCalc: "Tính KL có thể xếp",
  frtSimulator: "Mô phỏng cước",

  // ---------- Port Rotation ----------
  portRotation: "Lịch trình cảng",
  totalDuration: "Tổng thời gian",
  portNameCoord: "Tên cảng / Tọa độ",
  distanceTTLECA: "Quãng đường (TTL / ECA)",
  distanceECA: "Quãng đường / ECA",
  wf: "W.F",
  spd: "Spd",
  ldRate: "Tốc độ L/D",
  portIW: "Cảng (I / W)",
  dem: "Dem",
  des: "Des",
  portCharge: "Phí cảng",
  arrival: "Đến",
  departure: "Khởi hành",
  margin: "Biên",
  totals: "Tổng cộng",
  total: "Tổng",
  days: "Ngày",
  hours: "Giờ",
  portLocal: "Giờ địa phương",
  pcTime: "Giờ máy tính",
  portLocalTime: "Giờ địa phương cảng",
  utc: "UTC",

  // ---------- Operation Expense ----------
  operationExpense: "Chi phí khai thác",
  demDes: "Dem/Des",
  addComm: "Hoa hồng",
  brokerage: "Môi giới",
  freightTax: "Thuế cước",
  ballastBonus: "Thưởng Ballast",
  routingService: "Dịch vụ định tuyến",
  others: "Khác",
  cev: "C.E.V.",
  ilohc: "ILOHC",

  // ---------- Bunker Expense ----------
  bunkerExpense: "Chi phí nhiên liệu",
  bunkerIndex: "Chỉ số nhiên liệu",
  bunkerSimulator: "Mô phỏng nhiên liệu",
  recent: "Gần đây",
  pricePerMT: "Giá / MT",
  consumption: "Tiêu hao",
  expense: "Chi phí",

  // ---------- Result ----------
  result: "Kết quả",
  resultPlus: "Kết quả chi tiết",
  comparison: "So sánh",
  analyzer: "Phân tích",
  remark: "Ghi chú",
  hirePerDay: "Cho thuê / ngày",
  hAddComm: "H/Hoa hồng",
  netHire: "Cho thuê thực",
  offHire: "Ngưng thuê",
  cBase: "C/Base",
  revenue: "Doanh thu",
  opExpense: "CP khai thác",
  opProfit: "LN khai thác",
  totalHire: "Tổng cho thuê",
  totalExpense: "Tổng chi phí",
  profitRate: "Tỷ suất LN",
  profitUSD: "LỢI NHUẬN (USD)",

  // ---------- Time Charter ----------
  headCP: "Hợp đồng chính",
  subCP: "Hợp đồng phụ",
  headCPShort: "Head CP",
  subCPShort: "Sub CP",
  deliveryPort: "Cảng giao tàu",
  redeliveryPort: "Cảng trả tàu",
  duration: "Thời gian",
  dailyHire: "Cho thuê / ngày",
  grossHire: "Cho thuê gộp",
  useMultiDuration: "Dùng nhiều thời hạn",
  hire: "Cho thuê",
  operation: "Khai thác",
  tcBunkerCalc: "Máy tính tiêu hao TC",
  dailyGrossHire: "CT gộp/ngày",
  dailyNetHire: "CT thực/ngày",
  totalGrossHire: "Tổng CT gộp",
  totalNetHire: "Tổng CT thực",
  diff: "Chênh lệch",
  income: "Thu nhập",
  dailyRevenue: "DT / Ngày",
  dailyExpense: "CP / Ngày",
  dailyProfit: "LN / Ngày",
  deliveryTime: "Thời gian giao",
  redeliveryTime: "Thời gian trả",
  tcOut: "TC ra",

  // ---------- Loadable Quantity ----------
  loadableQtyTitle: "Tính khối lượng hàng có thể xếp",
  loadableQtyHelp:
    "Tính khối lượng hàng có thể xếp theo Grain/Bale, DWT hoặc Lumpsum. Nhấn biểu tượng tàu để nạp Thông số tàu. Giá trị nhỏ nhất giữa các cách tính sẽ được dùng làm khối lượng xếp.",
  volumeCalcTitle: "Tính theo thể tích — KL theo Grain / Bale",
  dwtCalcTitle: "Tính theo DWT — KL theo MT",
  loadingPortDraft: "Cảng xếp — Tính theo mớn",
  dischargingPortDraft: "Cảng dỡ — Tính theo mớn",
  grain: "Grain",
  bale: "Bale",
  stowageFactor: "Hệ số xếp hàng",
  loadableQuantity: "Khối lượng có thể xếp",
  deducted: "Khấu trừ",
  bunkerROB: "Nhiên liệu còn lại (FO + DO)",
  unpumpableBallast: "Ballast không bơm được",
  freshWater: "Nước ngọt",
  sagHog: "SAG / HOG",
  constant: "Hằng số",
  totalDeducted: "Tổng khấu trừ",
  mtLoadableQty: "KL có thể xếp (MT)",
  vesselDraft: "Mớn nước tàu",
  loadingPortDraftRestriction: "Mớn cảng xếp (giới hạn)",
  draftLossQty: "Lượng giảm do mớn",
  bunkerConsumption: "Tiêu hao nhiên liệu",
  freshWaterConsumption: "Tiêu hao nước ngọt",
  seaDaysTotal: "Tổng ngày biển",
  consumptionTotal: "Tổng tiêu hao",
  dischargingPortDraftShort: "Mớn cảng dỡ",
  draftDiffLoss: "Hao hụt do chênh mớn",
  ok: "Đồng ý",
  cancel: "Hủy",

  // ---------- New Vessel Dialog ----------
  newVessel: "Tàu mới",
  newVesselDesc:
    "Nhập đầy đủ các ô trống của Tốc độ và Tiêu hao nhiên liệu để tính dự toán hành trình.",
  vesselKind: "Loại tàu",
  vesselType: "Kiểu tàu",
  draft: "Mớn nước",
  estimatingValues: "Giá trị dự toán",
  general: "Thông tin chung",
  owner: "Chủ tàu",
  callSign: "Hô hiệu",
  imoNo: "Số IMO",
  vesselCode: "Mã tàu",
  hullNo: "Số thân tàu",
  beam: "Bề rộng",
  depth: "Chiều cao mạn",
  flag: "Quốc kỳ",
  class: "Cấp đăng kiểm",
  canal: "Kênh đào",
  gearHaHo: "Thiết bị & HA/HO",
  gearDesc: "Mô tả thiết bị",
  tankTopStrength: "Sức chịu nóc két (Trên/Giữa)",
  hatchCoverStrength: "Sức chịu nắp hầm",
  add: "Thêm",
  speed: "Tốc độ",
  bunkerConsumptionTitle: "Tiêu hao nhiên liệu",

  // ---------- Dev nav ----------
  navEstimation: "Dự toán",
  navOperation: "Khai thác",
  navTimeCharter: "Cho thuê định hạn",
  navLoadableQty: "KL có thể xếp",
  navCargoRelet: "Cargo Relet",

  // ---------- Status bar ----------
  reset: "Đặt lại",
  greatCircleLine: "Đường vòng cung lớn",
  antiPiracy: "Chống cướp biển",
  ecaInfo: "ECA : IMO, Mỗi quốc gia",
} as const;

// Lớp CSS dùng chung để đảm bảo font/cỡ chữ đồng nhất trên mọi form.
// CHUẨN THỐNG NHẤT: font-sans (hệ thống), 12px, leading-tight.
// Các selector con dùng `!important` để ép Input/Select/Textarea/Button
// (mặc định shadcn đang là text-base / md:text-sm) về đúng 12px,
// khớp với cỡ chữ số trong các bảng dữ liệu.
export const FONT_BASE = [
  "font-sans text-[12px] leading-tight",
  "[&_input]:!text-[12px] [&_input]:!font-sans",
  "[&_textarea]:!text-[12px] [&_textarea]:!font-sans",
  "[&_button]:!text-[12px] [&_button]:!font-sans",
  "[&_select]:!text-[12px] [&_select]:!font-sans",
  "[&_[role=combobox]]:!text-[12px] [&_[role=combobox]]:!font-sans",
  "[&_label]:!text-[12px]",
  "[&_h1]:!text-[12px] [&_h2]:!text-[12px] [&_h3]:!text-[12px] [&_h4]:!text-[12px]",
  "[&_th]:!text-[12px] [&_td]:!text-[12px]",
].join(" ");
